//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Управляющая_организация
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Управляющая_организация()
        {
            this.Объявления = new HashSet<Объявления>();
            this.Опросы = new HashSet<Опросы>();
        }
    
        public int ID_организации { get; set; }
        public int ID_пользователя { get; set; }
        public string Название { get; set; }
        public int Телефон { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Объявления> Объявления { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Опросы> Опросы { get; set; }
        public virtual Пользователь Пользователь { get; set; }
    }
}
